#!/usr/bin/env bash
# Usage: lcars fun:history [MM/DD]
# Summary: Prints random facts for a date
#
# NAME
#   lcars fun:history -- Prints random facts for a date
#
# SYNOPSIS
#   lcars fun:history [MM/DD]
#
# DESCRIPTION
#   lcars fun:history prints random facts for the specified date in MM/DD
#   format. If no date is provided, defaults to today's date.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

calendar_data() {
cat <<'EOF'
01/01	J.D. Salinger born, 1919
01/01	Paul Revere born in Boston, 1735
01/02	Isaac Asimov born in Petrovichi, Russian SFSR, 1920
01/04	George Washington Carver born in Missouri, 1864
01/04	Jakob Grimm born, 1785
01/04	Wilhelm Beer born, 1797, first astronomer to map Mars
01/05	DeWitt B. Brace born, 1859, inventor of spectrophotometer
01/06	Millard Fillmore's birthday (let's party!)
01/07	Nikola Tesla died in the Hotel New Yorker room 3327, 1943
01/10	Ethan Allen born, 1738
01/11	Alexander Hamilton born in Nevis, British West Indies, 1757?
01/12	"Long" John Baldry is born in London, 1941
01/13	Horatio Alger born, 1832
01/13	Sophie Tucker born, 1884
01/13	Wilhelm Wien born, 1864, Nobel prize for blackbody radiation laws
01/14	Albert Schweitzer born, 1875
01/15	Martin Luther King, Jr. born, 1929
01/17	Benjamin Franklin born in Boston, 1706
01/19	Edgar Allan Poe born in Boston, 1809
01/19	Robert Edward Lee born in Stratford Estate, Virginia, 1807
01/20	George Burns born, 1896
01/20	Dr. Mendeleev died with a pen in his hand, 1907
01/21	Lenin died, 1924
01/21	Thomas Jonathan "Stonewall" Jackson born in Clarksburg, VA, 1824
01/22	Sir Francis Bacon born, 1561
01/23	Ernst Abbe born, 1840, formulated diffraction theory
01/23	Grigori Yefimovich Rasputin born, 1869
01/23	Humphrey Bogart born in New York City, 1899
01/23	John Hancock born, 1737
01/23	Joseph Hewes born, 1730
01/23	Samuel Barber died, 1981
01/24	John Belushi is born in Chicago, 1949
01/25	Robert Burns born, 1759
01/25	Virginia Woolf born, 1882
01/25	W. Somerset Maugham born, 1874
01/27	Samuel Gompers born, 1850
01/30	Franklin Delano Roosevelt born in Hyde Park, New York, 1882
01/31	Jackie Robinson born, 1919
02/03	Gertrude Stein born, 1874
02/04	Ken Thompson, creator of unix, born, 1943
02/05	Alex Harvey (SAHB) is born in Glasgow, Scotland, 1935
02/06	King George VI of UK dies;  his daughter becomes Elizabeth II, 1952
02/07	Sinclair Lewis born, 1885
02/08	Friedleib F. Runge born, 1795, father of paper chromatography
02/08	John von Neumann died, 1957
02/08	Jules Verne born in Nantes, France, 1828
02/09	George Hartmann born, 1489, designed astrolabes, timepieces, etc.
02/10	Charles Lamb born, 1775
02/10	William Allen White born, 1868
02/11	Thomas Edison born, 1847
02/11	William Henry Fox Talbot (photographic pioneer) born, 1800
02/12	Abraham Lincoln born, 1809
02/12	Charles Darwin born in Shrewsbury, England, 1809
02/15	Galileo Galilei born in Pisa, Italy, 1564
02/15	Susan B. Anthony born, 1820
02/16	Pierre Bouguer born, 1698, founder of photometry
02/17	Frederic Eugene Ives born, 1856, pioneer of halftone
02/17	Marion Anderson born, 1902
02/17	T. J. Watson, Sr. born, 1874
02/18	Ernst Mach born, 1838, philosopher & optics pioneer
02/18	Michelangelo Buonarroti dies in Rome, Italy, 1564
02/19	Nicolas Copernicus born in Thorn, Poland, 1473
02/20	Ludwig Boltzmann born, 1844, atomic physics pioneer
02/21	Alexis De Rochon born, 1838, developed the spyglass
02/22	George Washington born, 1732
02/22	Pierre Jules Cesar Janssen born, 1824, found hydrogen in the sun
02/23	W.E.B. DuBois born, 1868
02/24	Winslow Homer born, 1836
02/24	Steve Jobs born, 1955
02/25	George Harrison born in Liverpool, England, 1943
02/25	Renoir born, 1841
02/26	Dominique Francois Jean Arago born, 1786; observed "Poisson's spot" cf June 21
02/28	Michel de Mantaigne born, 1533
02/29	Herman Hollerith born, 1860
03/01	David Niven born, 1910
03/02	Dr. Seuss born, 1904
03/04	Casimir Pulaski born, 1747
03/05	John Belushi dies in Los Angeles, 1982
03/05	Joseph Stalin died in Moscow, 1953
03/06	Michelangelo Buonarroti born in Caprese, Italy, 1475
03/07	Aristotle died, 322BC
03/07	Sir John Frederick William Herschel born, 1792, astronomer
03/08	Alvan Clark born, 1804, astronomer & lens manufacturer
03/08	Howard Aiken born, 1900
03/11	Robert Treat Paine born, 1737
03/11	Vannevar Bush born, 1890
03/11	Douglas Adams born in Cambridge, England, 1952
03/12	Gustav Robert Kirchhoff born, 1824, physicist
03/12	Terry Pratchett (Sir) dies, 2015, author
03/14	Albert Einstein born, 1879
03/14	Casey Jones born, 1864
03/14	Giovanni Virginia Schiaparelli born, 1835, astronomer; named Mars "canals"
03/14	Jean Baptiste Joseph Fourier born, 1768, mathematician & physicist
03/14	Karl Marx died, 1883
03/15	Andrew "Old Hickory" Jackson, 7th President of the United States, born in Waxhaw, South Carolina, 1767
03/15	J.J. Robert's Birthday in Liberia
03/16	George Clymer born, 1739
03/16	James Madison, 4th President of the United States, born in King George County, Virginia, 1751
03/19	Arthur C. Clarke died in Colombo, Sri Lanka, 2008
03/21	NetBSD project born, 1993
03/23	Pierre Simon de Laplace born, 1749, mathematician & astronomer
03/24	Harry Houdini born, 1874
03/26	Benjamin Thompson born, 1753, Count Rumford; physicist
03/26	David Packard died, 1996; age of 83
03/27	Maurits Cornelis Escher died, 1972
03/27	Stanislaw Lem died, 2006
03/27	Wilhelm Conrad Roentgen born, 1845, discoverer of X-rays
03/28	Pierre Simon de Laplace born, 1749, mathematician & astronomer
03/30	Francisco Jose de Goya born, 1746
03/30	Queen Elizabeth, the Queen Mother, died at the age of 101, 2002
03/30	Sean O'Casey born, 1880
03/30	Vincent Van Gogh born, 1853
03/31	Rene Descartes born, 1596, mathematician & philosopher
04/02	Hans Christian Andersen born, 1805, fairy tale author
04/02	Pope John Paul II (Karol Wojtyla) died in Vatican, 2005
04/03	Washington Irving born, 1783
04/05	Thomas Hobbes born, 1588, philosopher
04/08	Buddha born, 563 BC
04/08	David Rittenhouse born, 1732, astronomer & mathematician
04/09	Edward Muybridge born, 1830, motion-picture pioneer
04/09	J. Presper Eckert born, 1919
04/10	Commodore Matthew Calbraith Perry born, 1794
04/10	William Booth born, 1829, founder of the Salvation Army
04/13	Thomas Jefferson, 3rd President of the United States, born Shadwell Plantation, Albemarle County, Virginia, 1743
04/14	Christiaan Huygens born, 1629, physicist & astronomer; discovered Saturn's rings
04/15	Leonardo da Vinci born, 1452
04/15	Leonhard Euler born in Basel, 1707
04/16	Charles (Charlie) Chaplin (Sir) born in London, 1889
04/20	Adolf Hitler born, 1889
04/22	Kant born, 1724
04/22	Lenin born, the best friend of all the children, 1870
04/23	William Shakespeare died, 1616
04/26	William Shakespeare baptised, 1564
04/27	Louis Victor de Broglie born, 1774, physicist
04/28	James Monroe, 5th President of the United States, born in Westmoreland County, Viriginia, 1758
04/28	Terry Pratchett (Sir) born, 1948, author
04/29	Jules Henri Poincare born, 1854, founder of topology
04/29	William Randolph Hearst born in San Francisco, 1863
04/30	Karl Friedrich Gauss born, 1777, mathematician & astronomer
05/01	Little Walter (Marion Walter Jacobs) is born in Alexandria, Louisiana, 1930
05/02	Dr. Benjamin Spock born, 1903
05/04	Alice Liddell born, 1852, Alice's Adventures in Wonderland & Through the Looking-Glass
05/05	Karl Marx born, 1818
05/09	Pinza died, 1957
05/10	Fred Astaire (Frederick Austerlitz) born in Omaha, Nebraska, 1899
05/11	Johnny Appleseed born, 1768
05/12	Florence Nightingale born in Florence, Italy, 1820
05/13	Arthur S. Sullivan born, 1842
05/15	Mike Oldfield is born in Essex, England, 1953
05/18	Pope John Paul II (Karol Wojtyla) born in Wadowice, Poland, 1920
05/19	Ho Chi Minh born, 1890
05/21	Plato (Aristocles) born in Athens(?), 427BC
05/27	Hubert H. Humphrey born, 1911
05/28	Dionne quintuplets born, 1934
05/29	Gilbert Keith Chesterton born, 1874
05/29	John Fitzgerald Kennedy, 35th President of the United States, born in Brookline, Massachusetts, 1917
05/29	Patrick Henry born, 1736
05/30	Mel (Melvin Jerome) Blanc born in San Francisco, 1908
06/01	Brigham Young born, 1801
06/01	Marilyn Monroe born, 1926
06/02	Edward Elgar (Sir) born in Worcester, England, 1857
06/03	Henry James born, 1811
06/07	(Eugene Henri) Paul Gaugin born, 1848
06/07	George Bryan "Beau" Brummel born, 1778
06/07	Alan Mathison Turing died, 1954
06/08	Frank Lloyd Wright born in Richland Center, Wisconsin, 1867
06/13	Alexander the Great dies (323BC)
06/15	Edvard Hagerup Grieg born in Bergen, Norway, 1843
06/16	Hammurabi the Great dies, Babylon, 1686 BC
06/18	M.C. Escher born, 1898
06/19	FreeBSD project born, 1993
06/22	Carl Hubbell born, 1903
06/22	Meryl Streep born in Summit, New Jersey, 1949
06/22	Konrad Zuse born in Berlin, 1910
06/23	Alan Mathison Turing born, 1912
06/25	Eric Arthur Blair (a.k.a. George Orwell) born, 1903
06/27	Helen Keller born, 1880
07/03	Franz Kafka born, 1883
07/04	Nathaniel Hawthorne born in Salem, Massachusetts, 1804
07/04	John Adams and Thomas Jefferson die on same day, 1826
07/06	(Helen) Beatrix Potter born, 1866
07/06	John Paul Jones born, 1747
07/07	P.T. Barnum dies, 1891
07/08	Count Ferdinand von Zeppelin born, 1838
07/10	John Calvin born, 1509
07/10	Nikola Tesla born, 1856
07/11	John Quincy Adams, 6th President of the United States, born in Braintree, Massachusetts, 1767
07/12	Henry David Thoreau born, 1817
07/15	Clement Clarke Moore born, 1779, author of "A Visit from Saint Nicholas"
07/18	Brian Auger is born in London, 1939
07/20	Alexander the Great born, 356 BC
07/20	Bruce Lee died in Hong Kong, 1973
07/25	Robert Morris is born in Boston, 1932
07/25	Steve Goodman is born in Chicago, 1948
07/29	Mussolini born, 1883
07/30	Emily Bronte born, 1818
07/30	Henry Ford born, 1863
08/01	Herman Melville born, 1819
08/03	Lenny Bruce dies of a morphine overdose, 1966
08/05	Friedrich Engels died, 1895
08/06	Edsger Wybe Dijkstra died after a long struggle with cancer, 2002
08/06	Jonathan B. Postel is born in Altadena, California, 1943
08/08	Dustin Hoffman born in Los Angeles, 1937
08/12	Thomas Mann's Death, 1955
08/13	Alfred Hitchcock born, 1899
08/13	Annie Oakley born, 1860
08/13	Fidel Castro born, 1926
08/17	Mae West born, 1892
08/18	Meriwether Lewis born, 1774
08/20	Leon Trotsky assassinated, 1940
08/21	Christopher Robin Milne born, 1920
08/21	Winnie-the-Pooh (Edward Bear) born (given to Christopher Robin Milne), 1921
08/23	Gene Kelly born, 1912
08/27	Lyndon B. Johnson born, 1908
08/29	Oliver Wendell Holmes born, 1809, physician & father of the jurist
08/30	John W. Mauchly born, 1907
09/02	J.R.R. Tolkien died, 1973
09/05	King Louis XIV of France born, 1638
09/05	Raquel Welch born, 1942
09/06	Word is received that Perry has reached the North Pole and died, 1909
09/07	James Fenimore Cooper born in Burlington, NJ, 1789
09/07	Queen Elizabeth I of England born, 1533
09/08	Richard ``the Lionheart'', king of England born in Oxford, 1157
09/08	Peter Sellers born in Southsea, England, 1925
09/09	Chinese Communist Party Chairman Mao Tse-Tung dies at age 82, 1976
09/09	Dennis MacAlistair Ritchie, creator of C, born, 1941
09/12	Jesse Owens born, 1913
09/12	Stanislaw Lem born in Lwow, Poland, 1921
09/13	Walter Reed born, 1851
09/15	Agatha Christie born in Torquay, England, 1890
09/16	Allen Funt born in Brooklyn, NY, 1914
09/17	Ken Kesey born in La Junta, CO, 1935
09/18	Konstantin Eduardovich Tsiolkovsky born, 1857, father of rocket flight
09/18	Greta Garbo born, 1905
09/18	Jimi Hendrix dies from an overdose, 1970
09/18	Leonhard Euler died in St. Petersburg, 1783
09/19	President Garfield dies of wounds in Elberon, N.J., 1881
09/19	Konstantin Eduardovich Tsiolkovsky died, Russian SFSR, 1935
09/20	Upton (Beall) Sinclair born, 1878
09/21	H.G. (Herbert George) Wells born in Bromley, England, 1866
09/21	Louis Joliet born, 1645
09/22	President Garfield dies of wounds in Baltimore, 1881
09/23	Augustus (Gaius Octavius) Caesar born in Rome, 63 BC
09/23	Euripides born in Salamis, Greece, 480 BC
09/24	F. Scott Fitzgerald born, 1896
09/26	Johnny Appleseed born, 1774
09/26	T.S. (Thomas Stearns) Eliot born in St. Louis, 1888
09/27	Thomas Nast born, 1840
09/28	Michelangelo Buonarroti born in Caprese, Italy, 1573
09/28	Pompey (Gnaeus Pompeius Magnus) born in Rome, 106BC
09/28	Seymour Cray born, 1925
09/29	Gene Autry born, 1907
10/01	Jimmy Carter, 39th President of United States, born in Plains, Georgia, 1924
10/02	Aristotle dies of indigestion, 322 BC
10/02	Mohandas K. Gandhi born at Porbandar, Kathiawad, India, 1869
10/04	John V. Atanasoff born, 1903
10/05	Ray Kroc (founder of McDonald's) born, 1902
10/05	Steve Jobs died at the age of 56, 2011
10/12	Dennis MacAlistair Ritchie died at the age of 70, 2011
10/13	Lenny Bruce is born in New York City, 1925
10/13	Virgil (Publius Vergilius Maro) born near Mantua, Italy, 70 BC
10/14	Dwight David Eisenhower, 34th President of the United States, born in Denison, Texas, 1890
10/14	William Penn born in London, 1644
10/15	Pelham Grenville Wodehouse born, 1881
10/16	Noah Webster born, 1758
10/16	Oscar (Fingal O'Flahertie Wills) Wilde born in Dublin, 1854
10/16	Dr. Jonathan B. Postel dies at age 55, 1998
10/17	Richard Mentor Johnson born, 1780, 9th V.P. of U.S.
10/21	Alfred Nobel born in Stockholm, 1833
10/25	Pablo Picasso born in Malaga, Spain, 1881
10/27	James Cook is born, 1728
10/27	Theodore (Teddy) Roosevelt, 26th President of the United States, born New York, New York, 1858
10/27	Gerald M. Weinberg born, 1933
10/30	John Adams, 2nd President of the United States, born Quincy, Massachusetts 1735.
10/31	Chiang Kai-Shek born, 1887
10/31	Dale Evans born, 1912
11/01	Joseph Stalin's burial, 1961
11/02	Daniel Boone born near Reading, PA, 1734
11/04	King William III of Orange born, 1650
11/05	Roy Rogers born, 1912
11/09	Carl Sagan born, 1934
11/10	Martin Luther born in Eisleben, Germany, 1483
11/10	Soviet President Leonid Brezhnev dies at age 75, 1982
11/11	Fyodor Mikhailovich Dostoevsky born in Moscow, Russia, 1821
11/11	Kurt Vonnegut, Jr, born in Indianapolis, 1922
11/13	Robert Louis Stevenson born, 1850
11/13	St. Augustine of Hippo born in Numidia, Algeria, 354
11/18	Imogene Coca born, 1908
11/18	William S. Gilbert born, 1836
11/20	Robert Francis Kennedy (RFK) born in Boston, Massachusetts, 1925
11/26	Charles Schulz born in Minneapolis, 1922
11/26	Norbert Wiener born in Columbia, Missouri, 1894
11/27	Bruce Lee born in San Francisco, 1940
11/28	Friedrich Engels born, 1820
11/28	Joe Ossanna died, 1977
11/29	John Mayall is born in Cheshire, England, 1933
11/30	Cleopatra died, 30 BC
11/30	Mark Twain (Samuel Clemens) born in Florida, Missouri, 1835
12/01	Woody Allen (Allen Stuart Konigsberg) born in Brooklyn, NY, 1935
12/04	Tommy Bolin dies of a heroin overdose in Miami, 1976
12/05	Martin Van Buren, 8th President of the United States, born in Kinderhook, New York, 1837
12/05	Walt (Walter Elias) Disney born in Chicago, 1901
12/08	Horace (Quintus Horatius Flaccus) born in Venosa (Italy), 65BC
12/08	James (Grover) Thurber born in Columbus, Ohio, 1894
12/10	Emily Dickinson born, 1830
12/12	E.G. Robinson born, 1893
12/14	George Washington dies, 1799
12/16	Arthur C. Clarke born in Somerset, England, 1917
12/17	William Safire (Safir) born, 1929
12/18	Konrad Zuse died in Hünfeld, 1995
12/20	Carl Sagan died, 1996
12/21	Benjamin Disraeli born, 1804
12/22	Giacomo Puccini born, 1858
12/22	Joseph Vissarionnovich Djugashvili (Stalin) born, 1879
12/22	Samuel Beckett dies in Paris, 1989
12/23	Joseph Smith born, 1805
12/25	Isaac Newton (Sir) born in Grantham, England, 1642
12/26	Chas. Babbage born, 1791
12/28	John von Neumann born, 1903
12/29	Grigori Yefimovich Rasputin assasinated, 1916

01/01	AT&T officially divests its local Bell companies, 1984
01/01	The Epoch (Time 0 for UNIX systems, Midnight GMT, 1970)
01/03	Apple Computer founded, 1977
01/08	American Telephone and Telegraph loses antitrust case, 1982
01/08	Herman Hollerith patents first data processing computer, 1889
01/08	Justice Dept. drops IBM suit, 1982
01/10	First CDC 1604 delivered to Navy, 1960
01/16	Set uid bit patent issued, to Dennis Ritchie, 1979
01/17	Justice Dept. begins IBM anti-trust suit, 1969 (drops it, January 8, 1982)
01/24	DG Nova introduced, 1969
01/25	First U.S. meeting of ALGOL definition committee, 1958
01/26	EDVAC demonstrated, 1952
01/31	Hewlett-Packard founded, 1939
02/11	Last day of JOSS service at RAND Corp., 1966
02/14	First micro-on-a-chip patented (TI), 1978
02/15	ENIAC demonstrated, 1946
03/01	First NPL (later PL/I) report published, 1964
03/04	First Cray-1 shipped to Los Alamos
03/09	"GOTO considered harmful" (E.J. Dijkstra) published in CACM, 1968
03/14	LISP introduced, 1960
03/28	DEC announces PDP-11, 1970
03/31	Eckert-Mauchly Computer Corp. founded, Phila, 1946
04/01	Yourdon, Inc. founded, 1974 (It figures.)
04/03	IBM 701 introduced, 1953
04/04	Tandy Corp. acquires Radio Shack, 1963 (9 stores)
04/07	IBM announces System/360, 1964
04/09	ENIAC Project begun, 1943
04/28	Zilog Z-80 introduced, 1976
05/06	EDSAC demonstrated, 1949
05/01	First BASIC program run at Dartmouth, 1964
05/16	First report on SNOBOL distributed (within BTL), 1963
05/19	UNIX is 10000 days old, 1997
05/21	DEC announces PDP-8, 1965
05/22	Ethernet first described, 1973
05/27	First joint meeting of U.S. and European ALGOL definition cte., 1958
05/28	First meeting of COBOL definition cte. (eventually CODASYL), 1959
05/30	Colossus Mark II, 1944
06/02	First issue of Computerworld, 1967
06/07	Alan Mathison Turing died, 1954
06/10	First Apple II shipped, 1977
06/15	UNIVAC I delivered to the Census Bureau, 1951
06/16	First publicized programming error at Census Bureau, 1951
06/23	IBM unbundles software, 1969
06/23	Alan Mathison Turing born, 1912
06/30	First advanced degree on computer related topic: to H. Karamanian, Temple Univ., Phila, 1948, for symbolic differentiation on the ENIAC
07/08	Bell Telephone Co. formed (predecessor of AT&T), 1877
07/08	CDC incorporated, 1957
07/FriLast	System Administrator Appreciation Day
08/14	First Unix-based mallet created, 1954
08/14	IBM PC announced, 1981
08/22	CDC 6600 introduced, 1963
08/23	DEC founded, 1957
09/15	ACM founded, 1947
09/20	Harlan Herrick runs first FORTRAN program, 1954
10/02	First robotics-based CAM, 1939
10/06	First GPSS manual published, 1961
10/08	First VisiCalc prototype, 1978
10/12	Univac gives contract for SIMULA compiler to Nygaard and Dahl, 1962
10/14	British Computer Society founded, 1957
10/15	First FORTRAN Programmer's Reference Manual published, 1956
10/20	Zurich ALGOL report published, 1958
10/25	DEC announces VAX-11/780, 1977
11/04	UNIVAC I program predicts Eisenhower victory based on 7% of votes, 1952
12/08	First Ph.D. awarded by Computer Science Dept, Univ. of Penna, 1965

01/01	Anniversary of the Triumph of the Revolution in Cuba
01/01	Castro expels Cuban President Batista, 1959
01/01	Churchill delivers his "Iron Curtain" speech, 1947
01/01	First Rose Bowl; Michigan 49 - Stanford 0, 1902
01/02	Canada and the United States agree on a plan to preserve Niagara Falls, 1929
01/03	Benito Mussolini announces he is taking dictatorial powers over Italy, 1925
01/03	Margaret Thatcher becomes the longest-serving British Prime Minister in the 20th Century, 1988
01/04	Burma becomes independent from United Kingdom, 1948
01/04	Quadrantid meteor shower (look north)
01/05	-50 °F (-45.5 °C), Strawberry UT, 1913
01/05	The FCC hears the first demonstration of FM radio, 1940
01/05	Twelfth night
01/06	Maria Montessori opens her first school in Rome, 1907
01/07	First transatlantic telephone call, 1927
01/08	Battle of New Orleans
01/08	Monaco gains its independence, 1297
01/09	Plough Monday
01/10	First meeting of United Nations General Assembly in London, 1946
01/10	Thomas Paine's Common Sense published, 1776
01/11	Anniversary of the Peoples Republic of Albania
01/11	De Hostos' Birthday in Puerto Rico
01/11	Milk delivered in bottles for first time, 1878
01/11	Prithvi Jayanti in Nepal
01/11	US Surgeon General condemned cigarettes, 1964
01/11	The Whiskey-A-Go-Go opens on Sunset Boulevard in Los Angeles, 1963
01/12	Batman the TV series debuts on ABC, 1966
01/13	Mickey Mouse comic strip makes its first appearance, 1930
01/14	The first "Be-In" is held in Golden Gate Park, 1967
01/15	Angola becomes an independent state, 1975
01/16	Prohibition begins in the US, 1920
01/16	The Medici family are made official bankers of the Papacy, 1412
01/17	Captain James Cook becomes the first European explorer to cross the Antarctic Circle, 1773
01/18	Grey whale migration, California
01/18	The X-ray machine is exhibited for the first time, 1896
01/19	The last Volkswagen Beetle made in Germany leaves VW's plant, 1978
01/20	St. Agnes Eve (Ah, bitter chill it was...)
01/21	First commercial flight with a Concorde, 1976
01/22	British colonists reach New Zealand, 1840
01/23	The Royal Exchange opens in London, 1571
01/23	The Union of Utrecht forms a Protestant republic in the Netherlands, 1579
01/24	Eskimo Pie patented by Christian Nelson, 1922
01/24	Gold discovered in California at Sutter's Mill, 1848
01/24	Robert Baden-Powell begins the Boy Scout movement, 1908
01/25	The British Parliament passes the Constitutional Act of 1791 and splits the old province of Quebec into Upper and Lower Canada, 1791
01/26	Sydney, New South Wales settled, 1788
01/27	Grissom, White and Chaffe burned to death in Apollo 1, 1967
01/27	Vietnam War cease-fire signed, 1973
01/28	First ski tow, Woodstock VT, 1914
01/28	Space Shuttle Challenger (51-L) explodes 74 seconds after liftoff killing Scobee, Smith, McNair, Resnick, Jarvis, Onizuka, and McAuliffe, 1986
01/28	The first locomotive runs from the Atlantic to the Pacific on the Panama Railway, 1855
01/29	Liliuokalani is proclaimed Queen of Hawaii, the last monarch of Hawaii, 1891
01/30	Mohandas Gandhi assassinated in New Delhi by Hindu fanatic, 1948
01/30	Tet Offensive, 1968
01/31	"Ham" the chimpanzee soars into space aboard Mercury-Redstone 2, 1961
01/31	Dmitry Mendeleev established optimal alcohol-water mixture ratio in his PhD work on alcohol-water mixtures, 1865
01/31	Explorer I launched, 1958.  Van Allen Belt discovered
01/31	Irving Langmuir invented tungsten filament lamp, 1881
02/01	First TV soap: Secret Storm, 1954
02/01	Forces led by Khomeini take over Iran, 1979
02/01	Space Shuttle Columbia (STS-107) disintegrates 15 minutes before landing killing Husband, McCool, Chawla, Clark, Ramon, Brown, and Anderson, 2003
02/02	Adolf Hitler dissolves the German Parliament, 1933
02/03	The first commercial cheese factory is founded in Switzerland, 1815
02/04	Cybernet inaugurated, 1969
02/04	Patricia Hearst kidnapped by Symbionese Liberation Army, 1974
02/05	Gamel Abdel Nasser is nominated to be the first president of the United Arab Republic, 1958
02/06	Signing of the Treaty of Waitangi, founding document of New Zealand, 1840
02/07	The British Labour Party is formed, 1900
02/08	1963 Revolution Anniversary in Iraq
02/09	-51 °F (-46.1 °C), Vanderbilt MI, 1934
02/09	Gregory XV becomes Pope, the last Pope elected by acclamation, 1621
02/10	New Delhi becomes the capital of India, 1931
02/11	Norway's independence is proclaimed, marking the ultimate end of the Kalmar Union, 1814
02/12	China adopts the Gregorian calendar, 1912
02/12	Santa Barbara oil leak, 1969
02/13	France tests its first atomic bomb in Algeria, 1960
02/14	Bombing of Dresden, 1945
02/15	Chicago Seven convicted, 1970
02/16	Nylon patented, 1937
02/16	Stephen Decatur burns US frigate in Tripoli, 1804
02/17	The first ship passes through the Suez Canal, 1867
02/18	Joseph Goebbels delivers the Sportpalast Total War speech, 1943
02/18	Pluto discovered by Clyde Tombaugh, Lowell Observatory, AZ, 1930
02/19	Serfdom is abolished in Russia, 1861
02/19	US Marines land on Iwo Jima, 1945
02/20	FBI agent Robert Hanssen is arrested and charged with spying for Russia for 15 years, 2001
02/20	John Glenn orbits the Earth 3 times, 1962
02/21	Battle of Verdun begins, 1916 1M casualties
02/21	First telephone directory, New Haven, Connecticut, 1878
02/21	Malcom X shot to death in Harlem, 1965
02/22	Start of the Czechoslovak Revolution, 1948
02/23	Lt. Calley confesses his role in the Mỹ Lai massacre, implicates Cpt. Medina, 1971
02/24	Impeachment proceedings against Andrew Johnson begin, 1868
02/25	The Democratic Republic of Georgia occupied by Bolshevist Russia, 1921
02/26	Final radio broadcast of Dragnet, 1957
02/27	Richard The Lionheart crowned, 1189
02/28	The "French Connection" drug bust occurs in Marseilles, 1972
02/29	French and Indian raid on Deerfield MA, 1704
03/01	Sarah Goode, Sarah Osborne, and Tituba arrested for witchcraft in Salem, Massachusetts, 1692
03/01	The city of Rio de Janeiro is founded, 1565
03/02	Blackthorn winds (New England)
03/02	Ho Chi Minh is elected the President of North Vietnam, 1946
03/03	Bulgaria regains its independence from Ottoman Empire, 1878
03/04	Emile Berliner invents the microphone, 1877
03/04	First meeting of Congress in N.Y.C., 1789
03/05	Samuel Colt makes the first production-model revolver, 1836
03/06	The aspirin is registered as a trademark of Bayer, 1899
03/07	Mass protest outside the National Assembly of Kuwait building for women's voting rights in Kuwait, 2005
03/08	The first case of Spanish flu occurs, killing 50 million to 100 million people worldwide, 1918
03/09	The Barbie doll debuts, 1959
03/10	Republic of Côte d'Ivoire becomes a colony of France, 1893
03/11	Ceasefire declared in the war between Iran and Irak, 1988
03/12	The first bottles of Coca Cola were sold, 1894
03/13	"Striptease" introduced, Paris, 1894
03/14	Teddy Roosevelt excludes Japanese laborers from continental US, 1907
03/14	The kingdom of Cyprus is sold by the ruling Queen to Venice, 1489
03/15	Buzzards return to Hinckley OH
03/15	Day of the 1848 revolution in Hungary
03/15	France assumes protectorate over Vietnam, 1874
03/15	Watts, Los Angeles, riots kill two, injure 25, 1966
03/15	Ides of March.  Gaius Julius Caesar assassinated by senators, including adoptive son Marcus Junius Brutus Caepio, 44 BC
03/15	Watts, Los Angeles, riots kill two, injure 25, 1966
03/16	Largest coordinated worldwide vigil against the Iraq War, 2003
03/16	Mỹ Lai Massacre; 300 non-combatant villagers killed by US infantrymen, 1968
03/16	Robert Goddard launches first liquid-fueled rocket, Auburn MA, 1926
03/17	Invention of the rubber band, 1845
03/17	Ukrainian Nationalist Republic declared, 1917
03/17	Vanguard I launched, 1958.  Earth proved pear-shaped
03/18	Aleksei Leonov performs first spacewalk, 1965
03/18	In the Pyramid of Cheops a 4.400 year old mummy is found, 1989
03/19	Swallows return to Capistrano
03/20	Radio Caroline, the original British pirate radio station, sinks, 1980
03/21	Henry V becomes the king of England, 1413
03/22	First motion picture displayed by Auguste and Louis Lumière, 1895
03/22	World Day for Water
03/23	The first Islamic republic in the world is Pakistan, 1956
03/24	Construction of New York subway system begins, 1900
03/25	The first Bed-In for Peace by John Lennon and Yoko Ono, 1969
03/25	Triangle Shirt Waist Fire, 1911
03/26	Popeye statue unveiled, Crystal City TX Spinach Festival, 1937
03/26	The driving test is introduced, in the United Kingdom, 1934
03/27	Khrushchev becomes Premier of Soviet Union, 1958
03/28	Three Mile Island releases radioactive gas, 1979
03/29	Swedish settled Christiana (Wilmington) DE, 1638
03/29	The Republic of Ireland bans smoking in all work places, 2004
03/30	Alaska purchased from Russia for $7.2 million, 1867
03/30	Five rings around Uranus discovered, 1977
03/30	Pencil with eraser patented, 1858
03/31	The Eiffel Tower is inaugurated, 1889
04/01	People of superb intelligence, savoir-faire, etc. born this day.
04/02	Haile Selassie is proclaimed emperor of Ethiopia, 1930
04/03	First publication of the newspaper La Gazzetta dello Sport, 1896
04/04	Martin Luther King assassinated in Memphis, Tennessee, 1968
04/04	NATO established, 1949
04/05	Pocahontas marries English colonist John Rolfe in Virginia, 1614
04/06	Joseph Smith founds Mormon Church, 1830
04/07	Alewives run, Cape Cod
04/08	Matthew Flinders and Nicolas Baudin meet in Encounter Bay, 1802
04/08	The Venus de Milo is found on the island of Melos, 1820
04/09	Lee surrenders to Grant at Appomattox Courthouse, 1865
04/09	The first public exhibition of art opens in Paris, 1667
04/10	The Belfast Agreement is signed, on Good Friday, 1998
04/11	The Shogunate is abolished in Japan, 1868
04/12	Confederate troops fire first shots of Civil War at Ft Sumter, 1861
04/12	Great Britain adopts the Union Jack as their national flag, 1606
04/12	Space Shuttle Columbia launched, 1981
04/12	Yuri Gagarin becomes the first man in space, 1961
04/13	Laotian New Year (3 days) in Laos
04/14	US President Abraham Lincoln shot in Ford's Theatre by John Wilkes Booth, 1865
04/14	Titanic hits iceberg and sinks, 1912
04/15	Insulin first becomes generally available for use by diabetics, 1923
04/15	US President Abraham Lincoln dies, 1865
04/15	Ray Kroc opens first McDonalds in Des Plaines, IL, 1955
04/16	Syria becomes an independent Republic, 1946
04/17	Bay of Pigs invasion crushed by Castro forces, 1961
04/18	Albert Einstein dies, 1955
04/18	First Laundromat opens, Fort Worth Texas, 1934
04/18	San Francisco earthquake, 1906
04/18	The League of Nations is dissolved after 27 years, 1946
04/19	Landing of the 33 Patriots in Uruguay, 1825
04/19	Warsaw Ghetto uprising, 1943
04/20	In Bulgaria, the April Uprising takes place, 1876
04/20	Supreme Court unanimously rules in favor of busing, 1971
04/21	Lyrid meteor shower
04/21	Rome is founded by Romulus and Remus, 753 BC
04/22	Portuguese navigator Pedro Alvares Cabral becomes the first European to sight Brazil, 1500
04/22	The first Earth Day is celebrated, 1970
04/22	Vladimir Ilich Ulyanov, called Lenin, Russian political leader, born in Simbirsk, 1870
04/23	Bavarian co-rulers Duke Wilhelm IV and Duke Ludwig X proclaimed the weighty and consequential Bavarian Beer Purity Law (later Reinheitsgebot), 1516
04/23	Hank Aaron hits his first home run, 1954
04/24	The Greek enter Troy with the Trojan Horse, 1184BC
04/25	Integrated circuit patented by Robert Noyce, 1961
04/26	William Shakespeare baptized in Stratford-on-Avon, England, 1564, birthdate less certain
04/27	Magellan killed in Philippines, 1521
04/28	President of France, Charles de Gaulle resigns, 1969
04/29	Zipper patented by Gideon Sindback, 1913
04/30	Adolf Hitler and Eva Braun commit suicide, 1945
05/01	Beltaine; Feast of the god Bel, sun god
05/01	Adam Weishaupt founded the Illuminati of Bavaria, 1776
05/02	The first modern sighting of the Loch Ness monster is reported, 1933
05/03	Anti-war protest disrupts business in Washington, 1971
05/03	Jamaica is spotted by Christopher Columbus, 1494
05/04	Christopher Columbus sets foot on Jamaica, 1494
05/04	Kent State students Allison Beth Krause, Jeffrey Glenn Miller, Sandra Lee Scheuer, and William Knox Schroeder are killed by the Ohio National Guard, 1970
05/05	John Scopes arrested for teaching evolution, Dayton, TN, 1925
05/05	Kublai Khan becomes ruler of the Mongol Empire, 1260
05/06	Hindenburg explodes and burns upon landing at Lakehurst, NJ, 1937
05/07	Germany surrenders after World War II, 1945
05/08	Beginning of ostrich mating season
05/08	Herbert Akroyd Stuart patented the first "diesel" engine, 1890
05/08	US institutes mining of Haiphong Harbor, 1972
05/09	94 °F (34.4 °C), New York City, 1979
05/09	The first parliament of Australia opens in Melbourne, 1901
05/10	Germany invades Low Countries, 1940
05/10	Nazi bookburning, 1933
05/11	Thailand is no longer known as Siam, 1949
05/12	Tunisia becomes a French protectorate, 1881
05/13	Dutch statesman Johan van Oldenbarnevelt is executed in The Hague after having been accused of treason, 1619
05/14	Beginning of Lewis and Clark Expedition, 1804
05/14	Nation of Israel proclaimed, 1948
05/15	Asylum for Inebriates founded, Binghamton NY, 1854
05/15	The civil war in Finland ends, 1918
05/16	Root beer invented by Charles Elmer Hires, 1866
05/17	61cm (24") rain in 11 hours, Pearl River, S. China, 1982
05/17	Six Symbionese Liberation Army members killed in televised gun fight, 1974
05/18	Battle of Las Piedras in Uruguay, 1811
05/18	Napoleon crowned Emperor, 1804
05/19	The Legion d'Honneur is founded by Napoleon Bonaparte, 1802
05/20	The first modern atlas issued by Abraham Ortelius, 1570
05/21	Battle of Iquique in Chile, 1879
05/21	US explodes first hydrogen bomb, 1956
05/22	The transporting of British convicts to the New South Wales colony, is abolished, 1840
05/22	US Civil War ends, 1865
05/23	Israeli raid into Argentina to capture Adolf Eichmann, 1960
05/23	Two Yetis sighted, Mt. Everest, 1953
05/23	Federal Republic of Germany founded, 1949
05/24	Battle of Pinchincha in Ecuador, 1822
05/25	Oral Roberts sees 900 foot tall Jesus Christ, Tulsa OK, 1980
05/25	Successful test of the limelight in Purfleet, England, 1830
05/26	Congress sets first immigration quotas, 1924
05/26	John Calvin and his followers are expelled from Geneva, 1538
05/27	Golden Gate Bridge opens, 1937
05/27	The pop-up toaster patented by Charles Strite, 1919
05/28	Alan Turing submits On Computable Numbers for publication, 1936
05/29	Edmund Hillary and Tenzing Norkay climb Mt. Everest, 1953
05/29	First food stamps issued, 1961
05/30	US Marines sent to Nicaragua, 1912
05/30	Beginning of the civil war over Biafra, 1967
05/31	Yom Kippur War comes to an end by the signing of a disengagement agreement by Syria and Israel, 1974
06/01	In a referendum the Dutch reject the European Constitution, 2005
06/02	Denmark rejects the Maastricht Treaty in a close-call referendum, 1992
06/02	Native Americans "granted" citizenship, 1924
06/03	Edward White becomes the first American to perform a "Space Walk", 1965
06/03	Last Star Trek episode first aired ("Turnabout Intruder"), 1969
06/04	Roquefort cheese developed, 1070
06/05	Robert Kennedy assassinated, 1968
06/05	Titus and his Roman legions breach the middle wall of Jerusalem, 70
06/05	US leaves the Gold Standard, 1933
06/06	First drive-in movie, 1933
06/06	Normandy landing, 1944
06/07	The first act of civil disobedience by Gandhi, 1893
06/08	The Canadian Parliament meets for the first time in Ottawa, 1866
06/09	The Roman Emperor Nero commits suicide, 68
06/10	Death of Alexander the Great, 323 BC
06/10	Denver police tear gas Jethro Tull and 2000 fans at Red Rocks, 1971
06/12	Nelson Mandela is sentenced to life in prison, 1964
06/13	Much of Vancouver, British Columbia, is devastated by a fire, 1886
06/13	Pioneer 10 flies past Neptune on its way out of the Solar System, 1983
06/14	Sandpaper invented by I. Fischer, Jr., 1834
06/15	Ben Franklin's kite experiment, 1752
06/15	Magna Carta signed, 1215
06/15	Series of photographs by Edward Muggeridge prove to Leland Stanford that all the hooves of a horse are off the ground during the gallop, 1878
06/16	"The Blues Brothers" premieres in Chicago, 1980
06/16	Henry Ford launched the Ford Motor Company, 1903
06/17	China explodes its first hydrogen bomb, 1967
06/17	Watergate Democratic National Committee break-in, 1972
06/18	Winston Churchill delivers his "Finest Hour" speech, 1940
06/19	Julius and Ethel Rosenberg are executed in Sing-Sing prison, 1953
06/20	Lizzie Borden acquitted, 1893
06/20	Victoria crowned, 1837
06/21	Berlin airlift begins, 1948
06/21	Sun rises over Heelstone at Stonehenge
06/21	Civil rights workers James Chaney, Andrew Goodman, and Michael Schwerner are abducted and killed by KKK members in Philadelphia, Mississippi, 1964
06/22	The June Days Uprising in Paris begins, 1848
06/23	Harriet, Darwin's turtle died at the age of 176 years, 2006
06/23	Slavery de facto abolished in England, 1772
06/24	Senate repeals Gulf of Tonkin resolution, 1970
06/24	The capital of Jamaica, Kingston, is founded, 1664
06/25	Custer's Last Stand at Little Big Horn, 1876
06/25	North Korea invades South Korea, 1950
06/26	Battle of Gettysburg, 1863
06/26	St. Lawrence Seaway dedicated by Eisenhower & Queen Elizabeth II, 1959
06/26	Toothbrush invented, 1498
06/27	100 °F (37.7 °C), Fort Yukon, 1915
06/27	Bill Graham closes the Fillmore East, 1971
06/27	The world's first ATM is installed in Enfield, London, 1967
06/28	Archduke Franz Ferdinand of Austria assassinated in Sarajevo, marking the beginning of World War I, 1914
06/28	Supreme Court decides in favor of Allan Bakke in a case of strict race-based university admission quota, 1978
06/28	World War I ended with the signing of the Treaty of Versailles, 1919
06/29	The Seychelles gains independence from the United Kingdom, 1976
06/30	Tugunska explosion in Siberia at 7:17 local time, 1908
06/30	Albert Einstein publishes his theory of special relativity, 1905
06/30	China and Soviet Union announce split over ideology, 1960
07/01	Battle of Gettysburg begins, 1863
07/01	Hong Kong becomes a special administrative region of the People's Republic of China, 1997
07/01	The first day on the Somme marked the beginning of the Battle of the Somme, 1916
07/01	Warsaw Pact officially dissolved, 1991
07/02	Vermont abolishes slavery, as the first state, 1777
07/03	Dog days begin
07/04	Battles of Vicksburg and Gettysburg won by Union forces, 1863
07/04	Cloudy, 76 °F (24.4 °C), Philadelphia PA, 1776
07/04	New York abstains on Declaration of Independence vote, 1776
07/04	Thoreau enters woods, 1845
07/05	Bikini demonstrated for the first time, 1946
07/06	First `talkie' (talking motion picture) premiere in New York, 1928
07/06	Lawrence of Arabia captures Aqaba, 1917
07/07	First radio broadcast of "Dragnet", 1949
07/07	Terrorists detonate four bombs on London public transport, 2005
07/08	A UFO is believed to have crashed near Roswell, New Mexico, 1947
07/08	First public reading of the Declaration of Independence, 1776
07/08	Liberty Bell cracks while being rung at funeral of John Marshall, 1835
07/09	10-hour working day set by law, NH, 1847
07/09	The African Union gets established, 2002
07/10	134 °F (56.6 °C) in Death Valley, California, 1913
07/10	Most of London gets burned down in a severe fire, 1212
07/11	Mongolia gains independence from China, 1921
07/12	Minimum wages established: 40 cents/hour, 1933
07/13	Women first compete in Olympic games, 1908
07/14	Storming of the Bastille by the citizens of Paris, 1789
07/15	First item sold via Amazon.com, 1995
07/16	Detonation of the first atomic bomb at Alamagordo, NM, 1945
07/16	End of the civil war in Rwanda, 1994
07/17	Disneyland opens, 1955
07/18	"Mein Kampf" is published, 1925
07/18	Ty Cobb gets 4000th base hit, 1927
07/19	Sarah Good, Elizabeth Howe, Susannah Martin, Sarah Wildes, and Rebecca Nurse hanged for witchcraft, 1692
07/19	France declares war on Prussia, marking the beginning of the Franco-Prussian war, 1870
07/20	Armstrong and Aldrin land on moon, 1969
07/20	Ford Motor Company ships their car, 1903
07/21	First Train Robbery, Jesse James gets $3000 near Adair, Iowa, 1873
07/21	Vietnam divided at 17th parallel, 1954
07/21	Jury verdict in the Scopes Monkey Trial, 1925
07/22	Wiley Post becomes the first person to fly around the world, 1933
07/23	Ice cream cone introduced, St. Louis MO, 1904
07/25	First in-vitro fertilization baby born to Leslie and John Brown, 1978
07/26	Potsdam Declaration signed, 1945
07/27	The last Citroen 2CV made, 1990
07/28	Potato introduced in Europe by Sir Thomas Harriot, 1586
07/29	Inauguration of the Arc de Triomphe in Paris, 1836
07/30	"In God We Trust" made US motto, 1956
07/30	Elvis Presley performs for the first time in public, 1954
07/31	First U.S. patent issued, 1790
07/31	Harry S. Truman dedicates N.Y. Int'l Airport @ Idlewild Field, 1948, later JFK
08/01	Lughnasa; Feast of the god Lugh, a 30 day Celtic feast centers on this day
08/02	Hitler becomes the Fuehrer of Germany, 1934
08/03	Columbus sets sail for Cathay, 1492
08/03	USS Nautilus crosses under north polar ice cap, 1958
08/04	Axe murder of Andrew and Abbey Borden, 1892
08/04	Bombing of N. Vietnam begins, 1964
08/04	Britain declares war on Germany starting World War I, 1914
08/04	The French National Assembly abolishes feudal and ecclesiastical privileges, 1789
08/05	Nelson Mandela is jailed, 1962
08/06	Atomic bomb dropped on Hiroshima, 1945
08/06	Caricom in Barbados
08/06	Cy Young pitches first Major League Baseball game, 1890
08/07	Martha Tabram killed (likely but not certainly by Jack the Ripper), 1888
08/08	Montenegro declares war on Germany, 1914
08/08	Richard Nixon resigns the US presidency, 1974
08/08	The Great Train Robbery -- $7,368,000, 1963
08/09	Helter Skelter... the Charles Manson murders take place, 1969
08/09	Persia defeats Spartan King Leonidas at Thermopylae, 480 BC
08/09	US/Canada border defined in the Webster-Ashburton Treaty, 1842
08/09	Atomic bomb dropped on Nagasaki, 1945
08/09	Singapore secedes from Malaysia, 1965
08/10	Chicago incorporated as a village of 300 people, 1833
08/10	Major terrorist plot to destroy aircraft disrupted by Scotland Yard, 2006
08/10	US and Panama agree to transfer the canal in the year 2000, 1977
08/11	Dog days end
08/11	France Ends War in Indochina, 1954
08/11	Perseid meteor shower (look north; three days)
08/12	Cleopatra commits suicide, 30 BC
08/12	First test flight of Space Shuttle "Enterprise" from 747, 1977
08/12	Last US ground troops out of Vietnam, 1972
08/13	Berlin wall erected, 1961
08/13	Li'l Abner debut, 1934
08/14	France introduces motor vehicle registration, 1893
08/14	Social Security begins in US, 1935
08/15	Gandhi's movement obtains independence for Pakistan and India, 1947
08/15	Hurricane hits Plymouth Plantation, 1635
08/16	Roller Coaster patented, 1898
08/17	First public bath opened in N.Y., 1891
08/17	Indonesian Declaration of Independence, 1945
08/18	Lucy Page Gaston forms Anti-Cigarette League of America, 1899
08/18	Power blackout on Java, Indonesia, affects almost 100 million people, 2005
08/19	Air Force cargo plane snares payload from Discoverer 14 spy satellite, marking start of practical military reconnaissance from space, 1960
08/19	Gail Borden patents condensed milk, 1856
08/20	First commercial radio station airs in Detroit, Michigan, 1920
08/21	Louvre employee steals the "Mona Lisa", 1911
08/22	Death of King Richard III, 1485, Last of the Plantagenets
08/22	Joe Walker sets X-15 all time altitude mark (67 miles), 1963
08/22	St. Columba reports seeing monster in Loch Ness, 565
08/23	Sacco and Vanzetti executed, 1927
08/24	"Alice's Restaurant" premieres in New York and Los Angeles, 1969
08/24	-88.2 °C (-126.9 °F) at Vostok, Antarctica, 1960
08/24	British troops burn Washington, 1814
08/24	French forces under General Leclerc's command (including a company of mainly Spanish Republicans nicknamed "la Nueve") enter Paris, 1944
08/25	General de Gaulle makes a speech at the Paris city hall, 1944
08/26	19th amendment of US constitution gives women the vote, 1920
08/27	"Tarzan of the Apes" published, 1912
08/27	Krakatoa, Java explodes with a force of 1,300 megatons, 1883
08/28	Henry Hudson discovers Delaware Bay, 1609
08/28	Martin Luther King leads over 200,000 in civil rights rally in Washington, DC, 1963
08/29	Michael Faraday discovers electromagnetic induction, 1831
08/29	Star in Cygnus goes nova and becomes 4th brightest in sky, 1975; Nova Cygni 1975.
08/30	75 cents a pound tariff set on opium, 1842
08/30	Japan Stationery Co. sells first felt-tipped pen, 1960
08/30	St. Rose of Lima in Peru
08/30	Washington-to-Moscow hot line connected, 1963
08/31	269 people killed after Korean Airlines 747 shot down by USSR, 1983
08/31	Mary Anne Nichols becomes Jack the Ripper's first certain victim, 1888
08/31	Non-aggression pact signed by USSR and Afghanistan, 1926
08/31	Federation of Malaya gains independence from Great Britain, 1957
08/31	Independent union "Solidarność" ("Solidarity") formed, Gdansk, 1980
09/01	Bobby Fischer defeats Boris Spassky in World Chess Match, 1972
09/01	Joshua A. Norton proclaims himself 'Emperor Norton I', 1859
09/02	Great Britain adopts Gregorian Calendar, 1752
09/02	Japan signs unconditional surrender on US battleship `Missouri', 1945
09/03	Richard ``the Lionheart'' crowned king of England, 1189
09/03	Anniversary of the Founding of the Republic in San Marino
09/04	Napoleon III is deposed and the Third Republic is declared, 1870
09/05	US President Kennedy orders resumption of underground nuclear tests, 1961
09/05	St. Gotthard Tunnel opens in Switzerland, 1980
09/05	The first Continental Congress was convened in Philadelphia, 1774
09/06	149 Pilgrims set forth from England aboard the Mayflower, 1620
09/06	First Star Trek episode (The Man Trap) aired in Canada, 1966
09/06	US President McKinley shot, 1901
09/06	Somhlolo in Swaziland
09/07	Brazil declares its independence from Portugal, 1822
09/08	"Star Trek" debuts in the US on NBC, 1966
09/08	Jack the Ripper kills again, Annie Chapman is second victim, 1888
09/08	US President Gerald R. Ford pardons Richard M. Nixon, 1974
09/09	California becomes the 31st state of the USA, 1850
09/09	John Herschel takes the first glass plate photograph, 1839
09/09	United Colonies is renamed the United States, 1776
09/10	Mountain Meadows Massacre.  Mormons kill Gentile wagon train, 1857
09/11	CIA-sponsored terrorists overthrow Chilean government, murder President Allende, 1973
09/11	Terrorists destroy World Trade Center in New York, 2001
09/11	World Wide Fund (WWF) founded, 1961
09/12	German paratroopers rescue Mussolini from captivity in Rome, 1943
09/12	Germany annexes Sudetenland, 1938
09/13	58 °C (136.4 °F) measured at el Azizia, Libya, 1922
09/13	British defeat the French at the Plains of Abraham, just outside the walls of Quebec City, 1759
09/13	Building of Hadrian's Wall begun, 122
09/13	Jiǎng Jièshí (Wade-Giles: Chiang³ Chieh⁴-shih², known in the West as Chiang Kai-shek) becomes president of China, 1943
09/14	Benjamin Franklin is sent to France as an American minister, 1778
09/14	Salem, Massachusetts, is founded, 1629
09/14	The US Selective Service Act establishes the first peacetime draft, 1940
09/15	Soviet Premier Nikita Khrushchev begins his 13 day tour of the US, 1959
09/15	The US Foreign Affairs Dept. becomes the US State Department, 1789
09/15	The Nazis adopt a new national flag with the swastika, 1935
09/16	General Motors is founded, 1908
09/16	The village of Shawmut, Massachusetts, becomes the city of Boston, 1630
09/16	Malaya, Sabah, Sarawak and Singapore unite to become Malaysia, 1963
09/17	Battle of Antietam, 1862
09/17	Joshua A. Norton proclaims himself 'Emperor Norton I', 1859
09/18	Victory of Uprona in Burundi
09/19	New Zealand women get the right to vote, 1893
09/19	Walt Disney releases Steamboat Willie, 1928
09/20	Equal Rights Party nominates Belva Lockwood for US President, 1884
09/20	First meeting of the American Association for the Advancement of Science, 1848
09/20	First meeting of the US National Research Council, 1916
09/20	Magellan leaves Spain on the first Round the World passage, 1519
09/20	The Roxy Theater opens in Hollywood, 1973
09/21	J. R. R. Tolkien's The Hobbit is published, 1937
09/22	US President Lincoln issues the Emancipation Proclamation, 1862
09/22	Special prosecutor Leon Jeworski subpoenas US President Nixon, 1974
09/22	The first Soviet atomic bomb explodes, 1949
09/23	Philippine President Ferdinand Marcos declares martial law, 1972
09/23	The New York Knickerbockers becomes the first US Baseball club, 1845
09/23	US Vice President Nixon denies campaign fund fraud with his "Checkers" speech, 1952
09/24	The Netherlands surrenders New Amsterdam to England, 1664
09/25	Battle of Stamford Bridge marks the end of the Viking era, 1066
09/25	Sandra Day O'Connor becomes first woman on US Supreme Court, 1981
09/26	Concorde makes its first non-stop crossing of the Atlantic, 1973
09/27	The first passenger was hauled in a locomotive in England, 1825
09/28	"Pilgrim's Progress" published, 1678
09/28	A Greek soldier runs 26+ miles after the Persian defeat at Marathon, 490 BC
09/30	Jack the Ripper kills 2, Elizabeth Stride (#3) and Catherine Eddowes (#4), 1888
09/30	The first tooth is extracted under anesthesia in Charleston, Mass, 1846
09/30	The verdicts of the Nuremberg trials are announced, 1946
10/01	Austria issues the world's first postcards, 1869
10/01	NASA officially begins operations, 1958
10/02	Jacques Cartier discovers Montreal, Quebec, 1535
10/02	Thurgood Marshall sworn as the first black Supreme Court Justice, 1967
10/03	O. J. Simpson is found not guilty of murder, 1995
10/04	Crimean war begins, 1853
10/04	First space vehicle, Sputnik I, launched, 1957
10/05	Portugal declares itself a republic, 1910
10/06	Antioch College is the first US public school to admit Black and White men and women, 1853
10/06	Egyptian President Anwar es-Sadat is assassinated in Cairo, 1981
10/06	Israel is attacked by the alliance of Egypt and Syria, 1973
10/07	Foundation of the German Democratic Republic (GDR or DDR), 1949
10/07	Georgia Tech. beats Cumberland Univ. 222-0, 1916
10/07	Maryland Governor Marvin Mandel sent to prison on fraud charges, 1977
10/07	Mother Teresa of Calcutta awarded the Nobel Peace Prize, 1979
10/07	Police stop Wilbur Mills car, Fanne Fox jumps into water, 1974
10/08	Great Chicago Fire, 1871
10/08	San Marino adopts its written constitution, 1600
10/09	First two-way telephone conversation, 1876
10/10	Beginning of the Wars for Independence in Cuba
10/10	Foundation of the Workers Party in North Korea
10/10	Mercury at Superior Conjunction with Sun, moves into night sky, 1984
10/10	Spiro T. Agnew resigns as Vice-President due to income tax fraud, 1973
10/11	"Saturday Night Live" premiers on NBC-TV, 1975
10/11	The Gang of Four are arrested in Beijing, 1976
10/11	The first steam powered ferry ran between New York and Hoboken, 1811
10/11	The second Vatican Ecumenical Council opens in Rome, 1962
10/11	First broadcast of Saturday Night Live, 1975
10/12	Bahama Natives discover Columbus of Europe lost on their shores, 1492
10/12	Bavarian Crown Prince Ludwig married Princess Therese of Saxony-Hildburghausen, Oktoberfest, 1810
10/12	Khrushchev pounds his desk with shoe during a speech to the UN, 1960
10/12	Man O'War's last race, 1920
10/13	Italy declares war on Germany, 1943
10/13	US Navy born, 1775, authorized by the Second Continental Congress
10/14	Battle of Hastings won by William the Conqueror and the Normans, 1066
10/14	Chuck Yeager breaks sound barrier, 1947
10/15	Edison Electric Light Company begins operation, 1878
10/15	First draft card burned, 1965
10/16	The Walt Disney Company is founded by Walt Disney and his brother, Roy Disney, 1923
10/17	Al Capone convicted of income tax evasion, 1931
10/18	Soviets announce their probe took photos of the Moon's far side, 1959
10/18	The Grand Ole Opry opens its doors, 1925
10/19	Boston Shoemakers form first American labor organization, 1648
10/19	Mao Zedong (Wade-Giles: Mao Tse-tung) establishes the People's Republic of China, 1949
10/19	Napoleon's beaten army begins the long retreat from Moscow, 1812
10/20	"Saturday Night Massacre" resignation of US officials in protest against attempt to dismiss Watergate prosecutor, 1973
10/20	OPEC embargo, 1973
10/21	Edison makes the first practical incandescent lamp, 1879
10/21	Guggenheim Museum opens, 1959
10/22	Laos gains independence from France, 1953
10/23	Battle of Leyte Gulf begins, 1944
10/23	Day of the 1956 revolution in Hungary
10/23	South African troops invade Angola in support of UNITA and FNLA, 1975
10/23	Swallows leave Capistrano
10/24	Founding of the United Nations, 1945
10/25	The UN removes Taiwan and admits the People's Republic of China, 1971
10/26	UN's World Health Organization declares smallpox eradicated, 1978
10/27	New York's Boss Tweed is arrested on fraud charges, 1871
10/27	The first New York subway line is opened, 1904
10/27	Stock markets around the world crash because of fears of a global economic meltdown, 1997
10/28	Columbus gets to Cuba and meets inhabitants, 1492
10/28	Constantine's army defeats forces of Maxentius at Mulvian Bridge, 312
10/28	Harvard is founded in Massachusetts, 1636
10/28	Statue of Liberty is dedicated on Bedloe's Island, 1886
10/29	Leibniz makes the first use of the "long s" for integral, 1675
10/29	US stock market crash, 1929
10/30	Communist Party of Australia founded in Sydney, 1920
10/30	Orson Welles' "War of the Worlds" broadcast, 1938
11/01	First hydrogen bomb blasts Enewetak, 1952
10/31	Luther nails 95 Theses to door of Castle Church, Wittenberg, 1517
11/01	Austria-Hungary become two separate nations, 1918
11/01	Puerto Rican nationalists try to kill Truman at the Blair House, 1950
11/02	Luftwaffe completes 57 consecutive nights of bombing of London, 1940
11/02	Two Frenchmen make the first free hot air balloon flight, 1783
11/03	Beef rises to 3 cents a pound, IL, 1837
11/03	Linus Pauling wins Nobel Chemistry Prize, 1954
11/03	Sputnik II launched, 1957, bearing space dog Laika
11/04	Iranian militants seize US embassy personnel in Teheran, 1979
11/04	Soviet forces crush the anti-communist revolt in Hungary, 1956
11/05	Guy Fawkes' Plot, 1605
11/06	Anniversary of the October Socialist Revolution (2 days) in U.S.S.R.
11/07	Abolitionist newspaperman Elijah P. Lovejoy murdered by mob, 1837
11/07	Lewis and Clark Expedition in sight of the Pacific Ocean, 1805
11/08	Invasion of Sweden by Danish forces results in the Stockholm Bloodbath, 1520
11/09	Blackout of New York, New England, and Eastern Canada, 1965
11/09	Giant panda discovered (?!), China, 1927
11/09	Jack the Ripper kills fifth and final victim, Jane Kelly, 1888
11/09	Margaret Sanger forms American Birth Control League, 1921
11/09	Roosevelt establishes the Civil Works Administration, 1933
11/10	41 Women arrested in suffragette demonstrations near White House, 1917
11/10	Cpt. Wirz, commandant of Andersonville Prison hanged, 1865
11/10	Henry Stanley asks David Livingstone, "Dr. Livingstone, I presume?", 1871
11/11	First broadcast of Sesame Street, 1970
11/11	Washington becomes the 42nd state, 1889
11/12	Dr. Sun Yat-sen's Birthday in Taiwan
11/12	USA first exports oil to Europe, 1861
11/13	St. Brice's Day massacre by order of Ethelred, king of England, 1002
11/14	Czechoslovakia becomes a republic, 1918
11/14	Quarter Pounder price raised from $0.53 to $0.55 in violation of Nixon price controls (but okayed by Price Commission after formal request from McDonald's), 1971
11/15	First assembly of the League of Nations is held in Geneva, 1920
11/15	Niagara Falls power plant startup, 1896
11/16	Opening of the Suez Canal, 1869
11/16	Albert Hofmann synthesizes LSD in Switzerland, 1938
11/17	46,000 meteoroids fall over AZ in 20 minutes, 1966
11/17	Elizabeth I of England succeeds Queen Mary I of England, 1558
11/17	Richard Nixon says "I am not a crook.", 1973
11/18	Local standard time zones established for US, 1883
11/19	Gettysburg Address delivered, 1863
11/19	Samuel Goldwyn and Edgar Selwyn establish Goldwyn Company, 1916
11/20	Nuremberg Trials against 24 Nazi war criminals begin, 1945
11/21	Announcement of 18 1/2 minute gap on Watergate tape, 1973
11/21	Birmingham Pub Bombings by the IRA kill 21 people, 1974
11/22	John F. Kennedy is assassinated by Lee Harvey Oswald in Dallas, Texas, 1963
11/23	First broadcast of Dr. Who (longest running TV series), 1963
11/23	The first edition of Life is published. 1936
11/24	Lee Harvey Oswald is killed by Jack Ruby in Dallas, Texas, 1963
11/25	Alfred Nobel invents dynamite, 1867
11/26	Last flight ever with a Concorde made over Bristol, UK, 2003
11/27	Alfred Nobel establishes Nobel Prize, 1895
11/27	Friction match invented by Englishman John Walker, Sweden, 1826
11/27	Hoosac Railroad Tunnel completed, 1873, in NW Massachusetts
11/28	Albania declares its independence from the Ottoman Empire, 1912
11/29	King Tut's tomb opened, 1922
12/01	First national corn-husking championship, Alleman IA, 1924
12/01	Ford Motor Company introduces the first moving assembly line, 1913
12/01	Martin Luther King Jr., leads black boycott of Montgomery buses, 1955
12/01	Rosa Parks refuses to move to back of the bus (Montgomery, AL), 1953
12/02	Napoleon III becomes Emperor of the French, 1852
12/03	First neon light display, Paris, 1910
12/03	First successful human heart transplant led by Dr. Barnard, 1967
12/03	The Montreux Casino burns down during a Frank Zappa concert, 1971
12/04	People's Republic of China adopts its current constitution, 1982
12/04	Washington takes leave of his officers at Fraunce's Tavern, NYC, 1783
12/05	End of Prohibition, 1933 (at least the alcohol part)
12/05	Phi Beta Kappa founded, 1776
12/05	The Eighteenth Amendment repealed, ending Prohibition, 1933
12/06	London becomes the world's first city with motorised cabs, 1897
12/07	Japan bombs Pearl Harbor, 1941
12/08	Japan enters Second World War with invasion of Pantai Sabak, Kelantan, 1941
12/08	Romanian Constitution is adopted in a referendum, 1991
12/09	Ball-bearing roller skates patented, 1884
12/10	Metric system established in France, 1799
12/10	Nobel Peace Prize awarded each year
12/11	The British Parliament enacts the Statute of Westminster, 1931
12/12	First wireless message sent across Atlantic by Marconi, 1901
12/13	Apollo 17 leaves the moon, with "last" men to walk on moon aboard, 1972
12/13	Dartmouth College chartered, 1769
12/13	Geminid meteor shower (look south)
12/14	Portugal joins the United Nations, 1955
12/15	Argo Merchant oil spill, 1976
12/15	Bill of Rights adopted, 1791
12/15	James Naismith invents basketball, Canada, 1891
12/15	Sitting Bull shot in head while submitting to arrest, 1890
12/16	Pokemon episode (Electric Soldier Porygon) triggers attacks of photosensitive epilepsy in hundreds of Japanese children, 1997
12/17	Charles Dickens' A Christmas Carol is first published, 1843
12/18	Indonesia invades Netherlands New Guinea, 1961
12/19	Hitler becomes Supreme Commander-in-Chief of the German Army, 1941
12/20	Cheka founded, 1917
12/20	US buys ~1,000,000 sq. miles of Louisiana for ~$20/sq.mi.
12/21	Charles de Gaulle is elected President of France, 1958
12/21	Women gain the right to vote in South Australia, 1894
12/21	Women gain the right to hold political office in South Australia, 1894
12/22	First freight train is operated in Roorkee in India, 1851
12/23	The transistor is first demonstrated at Bell Laboratories, 1947
12/24	Hong Kong falls to the Japanese Imperial Army, 1941
12/24	KKK formed in Pulaski, Tenn, 1865
12/25	Christmas Island founded and named by Captain William Mynors, 1643
12/26	Data Processing Management Association founded as National Machine Accountants Association, 1951
12/27	APT report published, 1956
12/27	Ether first used as anesthetic in childbirth, 1845
12/28	Comet Kohoutek at perihelion, 1973
12/28	Proclamation of the Province of South Australia, 1836
12/28	Spain recognizes independence of Mexico, 1836
12/29	Battle of Wounded knee, 1890
12/29	Edison receives patent for Radio, 1891
12/30	First Los Angeles freeway dedicated, 1940
12/30	Israel and the Vatican establish diplomatic relations, 1993
12/30	Soviet Ukrainian Republic declared, 1917
12/31	St. Sylvester in Switzerland
12/31	First supersonic commercial flight by Tu-144, 1968
12/31	Windows tax in England, 1695
12/31	Winterland closes its doors, 1978

EOF
}

if [[ $# -eq 1 ]]; then
  date_arg="$1"
  if [[ ! "$date_arg" =~ ^[0-9]{1,2}/[0-9]{1,2}$ ]]; then
    echo "Error: Date must be in MM/DD format" >&2
    exit 1
  fi
  month=$(printf "%02d" "${date_arg%/*}")
  day=$(printf "%02d" "${date_arg#*/}")
  search_date="$month/$day"
  echo "Random Facts for $search_date"
else
  search_date="$(date '+%m/%d')"
  echo "Today's Random Facts"
fi

echo "===================="
echo
calendar_data | grep -h "^$search_date" | cut -f2 | awk '{ print "- " $0 }'

# FreeBSD Calendars license
#
# -------------------------------------------------------------------------------
#
# When the git repository containing this software was originally created it had
# been forgotten to add a license for it. Since this data comes from the src
# repository of FreeBSD, the same license applies.
#
# If in the past you have contributed to this code with different licensing
# assumptions, please inform the code maintainers so that they can license your
# contributions accordingly or remove them.
#
# The text of the license is reported below.
#
# -------------------------------------------------------------------------------
#
# #	@(#)COPYRIGHT	8.2 (Berkeley) 3/21/94
#
# The compilation of software known as FreeBSD is distributed under the
# following terms:
#
# Copyright (c) 1992-2022 The FreeBSD Project.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# The 4.4BSD and 4.4BSD-Lite software is distributed under the following
# terms:
#
# All of the documentation and software included in the 4.4BSD and 4.4BSD-Lite
# Releases is copyrighted by The Regents of the University of California.
#
# Copyright 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
# 	The Regents of the University of California.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
# This product includes software developed by the University of
# California, Berkeley and its contributors.
# 4. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# The Institute of Electrical and Electronics Engineers and the American
# National Standards Committee X3, on Information Processing Systems have
# given us permission to reprint portions of their documentation.
#
# In the following statement, the phrase ``this text'' refers to portions
# of the system documentation.
#
# Portions of this text are reprinted and reproduced in electronic form in
# the second BSD Networking Software Release, from IEEE Std 1003.1-1988, IEEE
# Standard Portable Operating System Interface for Computer Environments
# (POSIX), copyright C 1988 by the Institute of Electrical and Electronics
# Engineers, Inc.  In the event of any discrepancy between these versions
# and the original IEEE Standard, the original IEEE Standard is the referee
# document.
#
# In the following statement, the phrase ``This material'' refers to portions
# of the system documentation.
#
# This material is reproduced with permission from American National
# Standards Committee X3, on Information Processing Systems.  Computer and
# Business Equipment Manufacturers Association (CBEMA), 311 First St., NW,
# Suite 500, Washington, DC 20001-2178.  The developmental work of
# Programming Language C was completed by the X3J11 Technical Committee.
#
# The views and conclusions contained in the software and documentation are
# those of the authors and should not be interpreted as representing official
# policies, either expressed or implied, of the Regents of the University
# of California.
#
#
# NOTE: The copyright of UC Berkeley's Berkeley Software Distribution ("BSD")
# source has been updated.  The copyright addendum may be found at
# ftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change and is
# included below.
#
# July 22, 1999
#
# To All Licensees, Distributors of Any Version of BSD:
#
# As you know, certain of the Berkeley Software Distribution ("BSD") source
# code files require that further distributions of products containing all or
# portions of the software, acknowledge within their advertising materials
# that such products contain software developed by UC Berkeley and its
# contributors.
#
# Specifically, the provision reads:
#
# "     * 3. All advertising materials mentioning features or use of this software
#       *    must display the following acknowledgement:
#       *    This product includes software developed by the University of
#       *    California, Berkeley and its contributors."
#
# Effective immediately, licensees and distributors are no longer required to
# include the acknowledgement within advertising materials.  Accordingly, the
# foregoing paragraph of those BSD Unix files containing it is hereby deleted
# in its entirety.
#
# William Hoskins
# Director, Office of Technology Licensing
# University of California, Berkeley
