#!/usr/bin/env bash
# Usage: lcars hash:sha1
# Summary: Hashes a string or file contents using SHA-1
#
# NAME
#   lcars hash:sha1 -- Hashes a string or file contents using SHA-1
#
# SYNOPSIS
#   lcars hash:sha1
#
# DESCRIPTION
#   lcars hash:sha1 hashes a string or file contents using SHA-1.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

sha1() {
  if command -v sha1sum &> /dev/null; then
    sha1sum | awk '{ print $1 }'
  elif command -v shasum &> /dev/null; then
    shasum -a 1 | awk '{ print $1 }'
  else
    abort "No sha1sum or shasum found"
  fi
}

sha1 <<< "${1:-$(cat)}"
