#!/usr/bin/env bash
# Usage: lcars cli:commands
# Summary: Lists all LCARS commands
#
# NAME
#   lcars cli:commands -- list lcars commands
#
# SYNOPSIS
#   lcars cli:commands
#
# DESCRIPTION
#   This command is mostly used for `lcars help`.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

main() {
  local command_prefix="lcars-"
  shopt -s nullglob

  {
    PATH_remain="$PATH"
    # traverse PATH to find "lcars-" prefixed commands
    while true; do
      path="${PATH_remain%%:*}"

      if [[ -n "$path" ]]; then
        for lcars_command in "$path/$command_prefix"*; do
          echo "${lcars_command##*lcars-}"
        done
      fi

      [[ $PATH_remain == *:* ]] || break

      PATH_remain="${PATH_remain#*:}"
    done
  } | sort | uniq

  shopt -u nullglob
}

main "$@"
