#!/usr/bin/env bash
# Usage: lcars inspect:php:ext <extension>
# Summary: Checks if a PHP extension is installed
#
# NAME
#   lcars inspect:php:ext -- check if a PHP extension is installed
#
# SYNOPSIS
#   lcars-ig
#
# DESCRIPTION
#   lcars inspect:php:ext checks if a PHP extension is installed. Exits 0 if the
#   extension is installed, 1 if it is not.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

# set -euo pipefail
set -e

has_extension() {
  local extension="$1"

  if php:cli -m | grep -- "^$extension$" &> /dev/null; then
    echo installed
  else
    echo missing
  fi
}

main() {
  local arg output=()

  if [[ $# -eq 0 ]]; then
    php:cli -m | grep -v '^\[' | grep -v '^$' | sort | uniq
    return 0
  fi

  for arg in "$@"; do
    output+=("$(printf '%s\t%s' "$arg" "$(has_extension "$arg")")")
  done

  {
    printf '%s\t%s\n' "Extension" "Installed"

    for arg in "${output[@]}"; do
      printf '%s\n' "$arg"
    done
  } | column -t -s $'\t'

  if [[ ${output[*]} = *missing* ]]; then
    return 1
  else
    return 0
  fi
}

main "$@"
