#!/usr/bin/env bash
# Usage: lcars hash:sha256
# Summary: Hashes a string or file contents using SHA-256
#
# NAME
#   lcars hash:sha256 -- Hash a string or file contents using SHA-256
#
# SYNOPSIS
#   lcars hash:sha256
#
# DESCRIPTION
#   lcars hash:sha256 Hashes a string or file contents using SHA-256.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

sha256() {
  if command -v sha256sum &> /dev/null; then
    sha256sum | awk '{ print $1 }'
  elif command -v shasum &> /dev/null; then
    shasum -a 256 | awk '{ print $1 }'
  else
    abort "No sha256sum or shasum found"
  fi
}

sha256 <<< "${1:-$(cat)}"
