#!/usr/bin/env bash
# Usage: lcars util:copy
# Summary: Copies strings to the clipboard
#
# NAME
#   lcars util:copy -- It does something
#
# SYNOPSIS
#   lcars util:copy <string>
#   lcars util:copy <<< <string>
#   command | lcars util:copy
#
# DESCRIPTION
#   lcars util:copy copies the given string to the clipboard. It is a wrapper
#   around the `pbcopy` command on macOS, `xclip` on Linux, and `clip.exe` on
#   Windows.
#
# CREDITS
#   Based on https://github.com/zpm-zsh/clipboard

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

if command -v xclip >/dev/null 2>&1; then
  xclip -selection clipboard -in
elif command -v xsel >/dev/null 2>&1; then
  xsel -b
elif command -v wl-copy >/dev/null 2>&1; then
  wl-copy
elif command -v termux-clipboard-set >/dev/null 2>&1; then
  termux-clipboard-set
# WSL 1 or 2
elif [[ $OSTYPE == linux* && -r /proc/version && $(< /proc/version) == *[Mm]icrosoft* ]]; then
    clip.exe
elif [[ $OSTYPE == darwin* ]]; then
  command pbcopy
elif [[ $OSTYPE == cygwin* || $OSTYPE == msys ]]; then
  tee > /dev/clipboard
fi
