#!/usr/bin/env bash
# Usage: lcars hash:random
# Summary: Generates a random hash using OpenSSL
#
# NAME
#   lcars hash:random -- Generates a random hash using OpenSSL
#
# SYNOPSIS
#   lcars hash:random
#
# DESCRIPTION
#   lcars hash:random generates a random hash using OpenSSL's `rand` command.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

openssl rand -hex 32
