#!/usr/bin/env bash
# Usage: lcars cli:config:edit
#
# NAME
#   lcars cli:config:edit -- Opens the LCARS config file in $EDITOR
#
# SYNOPSIS
#   lcars cli:config:edit
#
# DESCRIPTION
#   lcars cli:config:edit opens the LCARS config file in your $EDITOR.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

: "${LCARS_CONFIG:="${XDG_CONFIG_HOME:-$HOME/.config}/lcars.json"}"

if [[ ! -f "$LCARS_CONFIG" ]]; then
  warn "Config file does not exist."
  warn "Create it?"

  read -r -p "[y/N] " response

  if [[ "$response" =~ ^[Yy]$ ]]; then
    warn "Creating config file..."
    touch "$LCARS_CONFIG"
    echo "{}" > "$LCARS_CONFIG"
    warn "Config file created."
  else
    abort "Exiting without creating config file."
  fi
fi

"$EDITOR" "$LCARS_CONFIG"
