#!/usr/bin/env bash
# Usage: lcars cli:commands
# Summary: Lists all LCARS commands
#
# NAME
#   lcars cli:commands -- list lcars commands
#
# SYNOPSIS
#   lcars cli:commands
#
# DESCRIPTION
#   This command is mostly used for `lcars help`.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

main() {
  shopt -s nullglob

  {
    for command in "$_LCARS_ROOT/libexec/lcars-"*; do
      if [[ -x "$command" ]]; then
        echo "${command##*/lcars-}"
      fi
    done
  } | sort

  shopt -u nullglob
}

main "$@"
