#!/usr/bin/env bash
# Usage: lcars-test:phpstan
# Summary: Runs PHPStan on PHP files in the project
#
# NAME
#   lcars-test:phpstan -- Run PHPStan on PHP files in the project
#
# SYNOPSIS
#   lcars-test:phpstan
#
# DESCRIPTION
#   lcars-test:phpstan runs PHPStan on PHP files in the project.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

composer exec -- phpstan analyse "$@"
