#!/usr/bin/env bash
# Usage: lcars app:console
# Summary: Opens the Tinker console
#
# NAME
#   console -- Run the Laravel Tinker REPL

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

php artisan tinker "$@"
