#!/usr/bin/env bash
# Usage: lcars cli:config:get <key>
#
# NAME
#   lcars cli:config:get -- Gets a local LCARS config
#
# SYNOPSIS
#   lcars cli:config:get <key>
#
# DESCRIPTION
#   lcars cli:config:get gets a local LCARS config.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}()}] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

: "${LCARS_CONFIG:="${XDG_CONFIG_HOME:-$HOME/.config}/lcars.json"}"

if [[ "${1:--a}" =~ ^(-a|--all)$ ]]; then
  jq 'del(.. | select(. == null or . == ""))' "$LCARS_CONFIG"
  exit 0
fi

key="$1"

jq --arg k "$key" -r  '.[$k]' \ "$LCARS_CONFIG" 2> /dev/null ||
  abort "Failed to read config file."
