#!/usr/bin/env bash
# Usage: lcars cli:config:get <key>
# Summary: Gets a local LCARS config
#
# NAME
#   lcars cli:config:get -- Gets a local LCARS config
#
# SYNOPSIS
#   lcars cli:config:get <key>
#
# DESCRIPTION
#   lcars cli:config:get gets a local LCARS config.

if [[ "$LCARS_DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

if [[ -z "$_LCARS_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/lcars-/lcars }' instead."
  exit 1
fi

set -euo pipefail

if [[ $# -ne 1 ]]; then
  exec lcars-cli:help -u cli:config:get
  exit 1
fi

if [[ "$1" =~ ^(-a|--all)$ ]]; then
  jq . "$(lcars:config:file)"
  exit 0
fi

lcars:config:get "$1"
