name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    name: Run test suite

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run shellcheck
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh extension install built-fast/gh-shellcheck
          gh shellcheck
          make test-man

      # - name: Run bats tests
      #   shell: 'script -q -e -c "bash {0}"'
      #   env:
      #     TERM: linux
      #   run: |
      #     bash --version
      #     bash -c "time ./test/setup"
      #     bash -c "time BATS_NO_PARALLELIZE_ACROSS_FILES=1 BATS_NUMBER_OF_PARALLEL_JOBS=2 ./test/bats/bin/bats -t test"
