name: Upload zip on new tag

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF##refs/tags/}" >> "$GITHUB_ENV"

      - name: Prepare zip archive
        run: FORMULA=lcars VERSION=${{ env.VERSION }} make archive

      - name: Upload archive to release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          files: pkg/lcars-${{ env.VERSION }}.zip

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.BUMP_APP_ID }}
          private-key: ${{ secrets.BUMP_APP_PRIVATE_KEY }}
          owner: built-fast
          repositories: homebrew-devtools
          permission-actions: write

      - name: Update homebrew tap
        run: |
          gh workflow run bump-formula.yml \
            -f formula=lcars \
            -f version=${{ env.VERSION }} \
            -f type=bash \
            -R built-fast/homebrew-devtools
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
